app:
  ai:
    provider: openai

spring:
  ai:
    model:
      chat: openai
      embedding: openai
    ollama:
      enabled: false
    openai:
      enabled: true
      api-key: ${OPENAI_API_KEY:}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
