app:
  ai:
    provider: ollama

spring:
  ai:
    model:
      chat: ollama
      embedding: ollama
    ollama:
      enabled: true
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
    openai:
      enabled: false
