spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/upgrader
    username: upgrader
    password: upgrader
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
